### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'add_bos_token'

### ISSUE THREAD

**Issue by Qin-xb** [OpenBMB/VisRAG#10]
When I run the example you provided, an error occurs.

Traceback (most recent call last):
  File "/data2/VisRAG/main.py", line 52, in <module>
    embeddings_query = encode(queries)
  File "/sdc/anaconda3/envs/VisRAG/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/data2/VisRAG/main.py", line 29, in encode
    outputs = model(**inputs)
  File "/sdc/anaconda3/envs/VisRAG/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/sdc/anaconda3/envs/VisRAG/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "../huggingface/modules/transformers_modules/VisRAG-Ret/modeling_visrag_ret.py", line 108, in forward
    model_inputs = self.fused_tokenize(
  File "../huggingface/modules/transformers_modules/VisRAG-Ret/modeling_visrag_ret.py", line 49, in fused_tokenize
    model_inputs = self._process_list(tokenizer, data_list, max_inp_length, padding_side="right")
  File "../huggingface/modules/transformers_modules/VisRAG-Ret/modeling_minicpmv.py", line 208, in _process_list
    self._convert_to_tensors(tokenizer, data, max_inp_length)
  File "../huggingface/modules/transformers_modules/VisRAG-Ret/modeling_minicpmv.py", line 175, in _convert_to_tensors
    if tokenizer.add_bos_token:
AttributeError: 'bool' object has no attribute 'add_bos_token'

**Comment by Qin-xb** [comment]
> 当我运行您提供的示例时，出现错误。
> 
> 回溯（最近一次调用最后一次）： 文件“/data2/VisRAG/main.py”，第 52 行，在 embeddings_query = encode（queries） 文件“/sdc/anaconda3/envs/VisRAG/lib/python3.10/site-packages/torch/utils/_contextlib.py”，第 116 行，在 decorate_context return func（*args，**kwargs） 文件“/data2/VisRAG/main.py”，第 29 行，在 encode output = model（**inputs） 文件“/sdc/anaconda3/envs/VisRAG/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1553 行，在 _wrapped_call_impl return self._call_impl（*args，**kwargs） 文件“/sdc/anaconda3/envs/VisRAG/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1562 行，在 _call_impl 中 返回 forward_call（*args，**kwargs） 文件“../huggingface/modules/transformers_modules/VisRAG-Ret/modeling_visrag_ret.py”，第 108 行，在 forward model_inputs = self.fused_tokenize（ 文件“../huggingface/modules/transformers_modules/VisRAG-Ret/modeling_visrag_ret.py”，第 49 行，在 fused_tokenize model_inputs = self._process_list（tokenizer，data_list，max_inp_length，padding_side =“right”） 文件“../huggingface/modules/transformers_modules/VisRAG-Ret/modeling_minicpmv.py”，第 208 行，在 _process_list self._convert_to_tensors(tokenizer、data、max_inp_length) 文件“../huggingface/modules/transformers_modules/VisRAG-Ret/modeling_minicpmv.py”，第 175 行，在 _convert_to_tensors if tokenizer.add_bos_token： AttributeError：'bool'对象没有属性'add_bos_token'

solve it，transformers==4.40.2 made it !!

**Comment by tcy6** [comment]
> > 当我运行您提供的示例时，出现错误。
> > 回溯（最近一次调用最后一次）： 文件“/data2/VisRAG/main.py”，第 52 行，在 embeddings_query = encode（queries） 文件“/sdc/anaconda3/envs/VisRAG/lib/python3.10/site-packages/torch/utils/_contextlib.py”，第 116 行，在 decorate_context return func（*args，**kwargs） 文件“/data2/VisRAG/main.py”，第 29 行，在 encode output = model（**inputs） 文件“/sdc/anaconda3/envs/VisRAG/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1553 行，在 _wrapped_call_impl return self._call_impl（*args，**kwargs） 文件“/sdc/anaconda3/envs/VisRAG/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1562 行，在 _call_impl 中 返回 forward_call（*args，**kwargs） 文件“../huggingface/modules/transformers_modules/VisRAG-Ret/modeling_visrag_ret.py”，第 108 行，在 forward model_inputs = self.fused_tokenize（ 文件“../huggingface/modules/transformers_modules/VisRAG-Ret/modeling_visrag_ret.py”，第 49 行，在 fused_tokenize model_inputs = self._process_list（tokenizer，data_list，max_inp_length，padding_side =“right”） 文件“../huggingface/modules/transformers_modules/VisRAG-Ret/modeling_minicpmv.py”，第 208 行，在 _process_list self._convert_to_tensors(tokenizer、data、max_inp_length) 文件“../huggingface/modules/transformers_modules/VisRAG-Ret/modeling_minicpmv.py”，第 175 行，在 _convert_to_tensors if tokenizer.add_bos_token： AttributeError：'bool'对象没有属性'add_bos_token'
> 
> solve it，transformers==4.40.2 made it !!

Yeah, we have tested the environment settings we provided to ensure that everything works well.
