### ISSUE TITLE
可以直接用通用训练的minicpm-v2.6作为特征提取模型吗，而不是用密集文档图片微调后的模型作为特征提取模型？

### ISSUE THREAD

**Issue by 1093842024** [OpenBMB/VisRAG#11]
原因：
     想验证在通用的（图片内容 + 图片文字）内容的RAG效果，而不是只在密集文字图片上应用。

如果直接使用通用图文大模型，需要修改通用图文大模型的源码来适配吗

**Comment by tcy6** [comment]
> 原因： 想验证在通用的（图片内容 + 图片文字）内容的RAG效果，而不是只在密集文字图片上应用。
> 
> 如果直接使用通用图文大模型，需要修改通用图文大模型的源码来适配吗

你的意思是说你想要使用MiniCPM-V2.6来检索图文混合信息，而不是只检索图片？

**Comment by 1093842024** [comment]
是的，要综合检索通用图片中的内容+文字信息

**Comment by 1093842024** [comment]
> > 原因： 想验证在通用的（图片内容 + 图片文字）内容的RAG效果，而不是只在密集文字图片上应用。
> > 如果直接使用通用图文大模型，需要修改通用图文大模型的源码来适配吗
> 
> 你的意思是说你想要使用MiniCPM-V2.6来检索图文混合信息，而不是只检索图片？

是的，要综合检索通用图片中的内容+文字信息

**Comment by tcy6** [comment]
> > > 原因： 想验证在通用的（图片内容 + 图片文字）内容的RAG效果，而不是只在密集文字图片上应用。
> > > 如果直接使用通用图文大模型，需要修改通用图文大模型的源码来适配吗
> > 
> > 
> > 你的意思是说你想要使用MiniCPM-V2.6来检索图文混合信息，而不是只检索图片？
> 
> 是的，要综合检索通用图片中的内容+文字信息

目前`VisRAG-Ret`是以`MiniCPM-V2.0`为基座训练的多模态检索模型，它原生是支持针对图文混合信息构建Index的，但是由于我们的训练数据只包含文本检索图片，因此可能需要在图文混合数据上进行微调来适应这一场景。

如果想要基于`MiniCPM-V2.6`训练检索模型，首先需要对其源码做一定修改，再在一定规模数据上进行微调。如果您的需求只是检索单张图片与文本的混合信息，而不是检索多张图片与文本的混合信息的话，我们建议您可以直接使用`VisRAG-Ret`，同时可以微调提升其在这一场景下的表现。
