### ISSUE TITLE
Is there any VisRAG-Gen sample code?

### ISSUE THREAD

**Issue by chying111** [OpenBMB/VisRAG#14]
There is only the VisRAG-Ret in the example. Could you please provide a sample code for generation?

**Comment by tcy6** [comment]
@chying111 No problem! please wait for a moment~

**Comment by tcy6** [comment]
@chying111 We’ve now released our `VisRAG Pipeline` as a Google Colab demo. You can try it out here: [VisRAG Pipeline Demo on Colab](https://colab.research.google.com/drive/11KV9adDNXPfHiuFAfXNOvtYJKcyR8JZH?usp=sharing).
