### ISSUE TITLE
A question about computing similarity score during retrievaling.

### ISSUE THREAD

**Issue by chenbuhuu** [OpenBMB/VisRAG#15]
In ur paper,the similarity score during retrievaling is calculated by the cosine similarity.While when I read the class DRTrainer in "dense_trainer.py",it is calculated by dot product.If I understand the code correctly, I hope you to pay attention to this.

**Comment by tcy6** [comment]
@chenbuhuu Good question! Actually, during the training of `VisRAG-Ret`, we apply `weighted mean pooling` on the `last_hidden_states`, followed by `normalization`. Under this condition, `cosine similarity` and `dot product` become equivalent.
