### ISSUE TITLE
VisRAG-Gen测试代码问题

### ISSUE THREAD

**Issue by Aeryn666** [OpenBMB/VisRAG#18]
作者你好，请问我在运行VisRAG/scripts/generate/generate.py的代码时，发现代码第87、88行有一些不明白的地方，想请教一下：
![image](https://github.com/user-attachments/assets/96418dbe-8416-45fa-94dd-6ca9900302d1)
请问图中所示的query_path和corpus_path是从hf上下载下来的openbmb/VisRAG-Ret-Test-ArxivQA吗？
但是，我没有在这个数据集里找到适合代码里的文件呢
![image](https://github.com/user-attachments/assets/ba6ce5a3-f4b2-4431-8522-ea2e054a65a8)
请问这里的query_path和corpus_path应该是什么呢，谢谢作者🙏

**Comment by tcy6** [comment]
十分抱歉给你造成了困扰，事实上`corpus`和`queries`文件夹下面的`parquet`文件便是你所需的文件，现在我已经修改了`generate.py`中加载数据集的逻辑，使其更加简洁和清晰，你可以下载并使用最新的`generate.py`代码

**Comment by Aeryn666** [comment]
> 十分抱歉给你造成了困扰，事实上`corpus`和`queries`文件夹下面的`parquet`文件便是你所需的文件，现在我已经修改了`generate.py`中加载数据集的逻辑，使其更加简洁和清晰，你可以下载并使用最新的`generate.py`代码

特别感谢你的回答，我现在已经解决这个问题了，谢谢谢谢～

**Comment by tcy6** [comment]
> > 十分抱歉给你造成了困扰，事实上`corpus`和`queries`文件夹下面的`parquet`文件便是你所需的文件，现在我已经修改了`generate.py`中加载数据集的逻辑，使其更加简洁和清晰，你可以下载并使用最新的`generate.py`代码
> 
> 特别感谢你的回答，我现在已经解决这个问题了，谢谢谢谢～

@Aeryn666 不客气～
