### ISSUE TITLE
从多个文件(含多个带图的PDF，word，Excel)中综合分析可以吗？

### ISSUE THREAD

**Issue by tqangxl** [OpenBMB/VisRAG#20]
如给一个文档路径，含上市企业的年报，公示，财务数据，同时在线搜索官方的数据分析行业情况，
最后综合分析企业未来的发展空间，财务发展趋势之类的

**Comment by tcy6** [comment]
@tqangxl 可以的，只需将多个文件转换成pdf (word, excel可以通过office自带的导出功能转换为pdf)。请稍等，相关代码马上开源。

**Comment by tcy6** [comment]
@tqangxl 您好，我们已经在仓库中添加了`VisRAG Pipeline`相关的代码，具体路径位于`VisRAG/scripts/demo/visrag_pipeline`，您可以首先使用`build_index.py`来处理您的若干文档 (它们均已被转换为pdf)，再使用`answer.py`文件进行多轮问答。
