### ISSUE TITLE
Can you understand the entire document content

### ISSUE THREAD

**Issue by smileyboy2019** [OpenBMB/VisRAG#21]
A PDF has dozens of pages, can you read the entire article from beginning to end. For example, a novel can be summarized from beginning to end,.
Second question: If there are two PDFs, can we compare them to see if there are any differences between them.

**Comment by tcy6** [comment]
@smileyboy2019 We regret that our current VisRAG system does not support these two functionalities at this time. However, to the best of my knowledge, LightRAG or GraphRAG may be equipped to handle such tasks. Enhancing VisRAG with these capabilities is indeed a priority in our future development efforts～
