### ISSUE TITLE
关于跑通整个VisRAG流程问题

### ISSUE THREAD

**Issue by liuchunming2** [OpenBMB/VisRAG#22]
您好，我认为您的论文非常棒，但是我想通过VisRAG输入一个问题和pdf去生成结果，但是没有找到很详细的教程，请问您能给我讲一下大概的流程吗，运行哪些代码？

**Comment by juebingliu** [comment]
看/scripts/demo/visrag_pipline这个目录下的代码就行，顺序是先运行build_index.py，再运行answer.py

**Comment by liuchunming2** [comment]
> 看/scripts/demo/visrag_pipline这个目录下的代码就行，顺序是先运行build_index.py，再运行 answer.py

好的谢谢您，请问知识库路径要输入什么呢，我们自己定义的知识库吗，如果是我们自己定义的，那知识库是什么样子的呢

**Comment by juebingliu** [comment]
需要输入两个路径，一个是你存放PDF文件的knowledge_base_path，另外一个是index生成的路径

**Comment by juebingliu** [comment]
> 需要输入两个路径，一个是你存放PDF文件的knowledge_base_path，另外一个是index生成的路径

运行那两个py文件的时候会有提示

**Comment by liuchunming2** [comment]
> > 需要输入两个路径，一个是你存放PDF文件的knowledge_base_path，另外一个是index生成的路径
> 
> 运行那两个py文件的时候会有提示

![1731659156298](https://github.com/user-attachments/assets/f7832b46-6480-434d-8210-fa6de9c8d5bf)
请问，我在运行answer.py的时候出现这个错误是什么原因呢
