### ISSUE TITLE
训练流程问题

### ISSUE THREAD

**Issue by eternal-god3** [OpenBMB/VisRAG#23]
我想请问一下此处trainer的问题是否是源码编写有误？
[rank2]: Traceback (most recent call last):
[rank2]:   File "/home/lzr24/VisRAG-master/src/openmatch/driver/train.py", line 152, in <module>
[rank2]:     main()
[rank2]:   File "/home/lzr24/VisRAG-master/src/openmatch/driver/train.py", line 145, in main
[rank2]:     trainer.train()
[rank2]:   File "/home/lzr24/miniconda3/envs/VisRAG/lib/python3.10/site-packages/transformers/trainer.py", line 2123, in train
[rank2]:     return inner_training_loop(
[rank2]:   File "/home/lzr24/miniconda3/envs/VisRAG/lib/python3.10/site-packages/transformers/trainer.py", line 2481, in _inner_training_loop
[rank2]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank2]: TypeError: DRTrainer.training_step() takes 3 positional arguments but 4 were given

**Comment by tcy6** [comment]
@eternal-god3 您好，经过我们测试，我们编写的代码是可以顺利跑通的。您是否检查过各个库的版本是否与我们requirements.txt中相一致呢，比方说transformers是4.40.2版本吗

**Comment by eternal-god3** [comment]
> @eternal-god3 您好，经过我们测试，我们编写的代码是可以顺利跑通的。您是否检查过各个库的版本是否与我们requirements.txt中相一致呢，比方说transformers是4.40.2版本吗

问题解决了 感谢

**Comment by tcy6** [comment]
@eternal-god3 不客气～
