### ISSUE TITLE
运行answer.py的时候出现错误

### ISSUE THREAD

**Issue by liuchunming2** [OpenBMB/VisRAG#24]
![Uploading 1731660583700.png…]()
我在运行完cripts/demo/visrag_pipeline/build_index.py后，在运行/scripts/demo/visrag_pipeline/answer.py出现上图中的错误，请问您能告诉我解决方法吗

**Comment by liuchunming2** [comment]
我下载的模型是MiniCPM-V-2

**Comment by liuchunming2** [comment]
![1731660583700](https://github.com/user-attachments/assets/8b9dd12b-cd57-49ea-b591-55c127c61d15)

**Comment by tcy6** [comment]
@liuchunming2 您好，出现这个问题的原因是您将`answer.py`中的生成模型由`MiniCPM-V-2_6`替换为了`MiniCPM-V-2` （二者的接口不一致，因此出现了报错）。因为`MiniCPM-V-2_6`支持原生多图联合理解，因此我们将其作为默认的生成模型。我们将会尽快更新代码，使其支持`MiniCPM-V-2`的`Weighted Selection`生成方式～
