### ISSUE TITLE
Can u provide a tutorial to generate dataset with ones's own data for training?

### ISSUE THREAD

**Issue by zhuyr97** [OpenBMB/VisRAG#25]

**Comment by tcy6** [comment]
@zhuyr97 Thank you for your interest! We plan to open-source the relevant code in the next few days, which will allow you to easily generate datasets using your own data for training. Stay tuned!

**Comment by zhuyr97** [comment]
thanks! Fine-tuning with one's own data based on the open weights of Vis-Ret is something many people would find interesting!

**Comment by tcy6** [comment]
> thanks! Fine-tuning with one's own data based on the open weights of Vis-Ret is something many people would find interesting!

Totally agree!

**Comment by tcy6** [comment]
Apologies for the long wait. We have now released the relevant code for generating training data for `VisRAG-Ret` using `GPT-4o`. The code is available in `scripts/data/batch_api.py`. Before running this script, please save each page of the PDF files you wish to use as training data in JSON format, ensuring that each JSON file contains an `image_base64` field. All these JSON files should be placed in the `input_dir`. After that, you can execute the script by running:

```bash
python batch_api.py input_dir output_dir
```
This will generate queries for each page and save them as files in the `output_dir`.

**Comment by tcy6** [comment]
> > @zhuyr97 Apologies for the long wait. We have now released the relevant code for generating training data for `VisRAG-Ret` using `GPT-4o`. The code is available in `scripts/data/batch_api.py`. Before running this script, please save each page of the PDF files you wish to use as training data in JSON format, ensuring that each JSON file contains an `image_base64` field. All these JSON files should be placed in the `input_dir`. After that, you can execute the script by running:
> > ```shell
> > python batch_api.py input_dir output_dir
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will generate queries for each page and save them as files in the `output_dir`.
> 
> The file `batch_api.py `provides a pipeline to generate training data in JSON format. However, it would be beneficial to provide a pipeline for generating training data in Parquet format, as this is the default format used in this repository. Are there any differences or gaps between these two pipelines?

Your suggestion is great, and we will work on improving the code as soon as possible. Regarding the data generation, there is only one pipeline, which is the one we have currently provided. The Parquet files are generated later for easier visualization of images on Hugging Face.

**Comment by zhuyr97** [comment]
thanks! I also send more detailed questions via email.   （yus21@mails.tsinghua.edu.cn ） @tcy6

**Comment by katie312** [comment]
> [@zhuyr97](https://github.com/zhuyr97) Apologies for the long wait. We have now released the relevant code for generating training data for `VisRAG-Ret` using `GPT-4o`. The code is available in `scripts/data/batch_api.py`. Before running this script, please save each page of the PDF files you wish to use as training data in JSON format, ensuring that each JSON file contains an `image_base64` field. All these JSON files should be placed in the `input_dir`. After that, you can execute the script by running:
> 
> python batch_api.py input_dir output_dir
> This will generate queries for each page and save them as files in the `output_dir`.

有考虑用开源模型做一个方案吗？类似minicpm-v，效果应该不会相差太多？gpt4o还是有点贵🥲 正在尝试改成用本地开源模型做生成
