### ISSUE TITLE
Parquet files in generation.py

### ISSUE THREAD

**Issue by cagey-squirrel** [OpenBMB/VisRAG#26]
How to access parquet data for generation.py script?
I am trying to run generation script but I am running into an issue of 
FileNotFoundError: [Errno 2] No such file or directory: 'image/ChartQA/ChartQA-eval-queries.parquet
Is this data supposed to be downloaded from elsewhere or how else do I access it?

**Comment by tcy6** [comment]
@cagey-squirrel Yes, you’ll need to download the necessary files from Hugging Face. Our model and all associated data can be found in the [VisRAG collection](https://huggingface.co/collections/openbmb/visrag-6717bbfb471bb018a49f1c69).

Regarding the specific error you mentioned, the Parquet file containing the ChartQA dataset queries is located [here](https://huggingface.co/datasets/openbmb/VisRAG-Ret-Test-ChartQA/tree/main/queries).

Let us know if you have further questions!
