### ISSUE TITLE
Script for running generation

### ISSUE THREAD

**Issue by cagey-squirrel** [OpenBMB/VisRAG#29]
Is it possible to update `generation.py` such that it can run just by providing command line arguments, similar to how retrieval script works?

I am not sure what is the purpose of `input_dir` and `model_name_or_path` variables. If I defined a `model_name` in command line arguments I would expect that model name to be used to pull the model from HF. 

Also, where can I get trec files that are supposed to be in `results_root_dir` dir? I cannot see them on HF collection.

Thank's for the answers in advance! :)

**Comment by tcy6** [comment]
@cagey-squirrel Hey! We've updated `generate.py` to make its logic and guidance much clearer. Feel free to check it out and give it a try—hope it helps!
