### ISSUE TITLE
输入问题和pdf样例

### ISSUE THREAD

**Issue by liuchunming2** [OpenBMB/VisRAG#30]
你好，我成功运行了VisRAG-master/scripts/demo/visrag_pipeline，请问您这里是否有官方的测试样例，输入问题和pdf，如果有，请您告诉我一下样例的路径。

**Comment by liuchunming2** [comment]
为什么你的数据集都是图片呢，VisRAG-master/scripts/demo/visrag_pipeline这个路径下的代码输入的是pdf

**Comment by tcy6** [comment]
> 你好，我成功运行了VisRAG-master/scripts/demo/visrag_pipeline，请问您这里是否有官方的测试样例，输入问题和pdf，如果有，请您告诉我一下样例的路径。

@liuchunming2 您好，有官方的测试样例的，您可以从[VisRAG Pipeline Space](https://huggingface.co/spaces/tcy6/VisRAG_Pipeline)处下载`car_owner_manual.pdf`文件，这是一本汽车的车主手册。

**Comment by tcy6** [comment]
> 为什么你的数据集都是图片呢，VisRAG-master/scripts/demo/visrag_pipeline这个路径下的代码输入的是pdf

@liuchunming2 关于我们的数据集，因为模型不能接受PDF作为输入，因此我们将原本不是图片的PDF数据中的每一页均渲染成了图片。`scripts/demo/visrag_pipeline`的目的是为了演示如何基于用户的知识库搭建`VisRAG`，考虑到PDF是一种较为通用的格式 (PPT, Word, Excel均可导出为PDF格式，大多数电子文档也都是PDF格式)，因此我们的代码仅仅考虑基于PDF搭建知识库。不知这样能否解答您的疑惑
