### ISSUE TITLE
Support more models as retrievers？

### ISSUE THREAD

**Issue by WGowi** [OpenBMB/VisRAG#31]
With the development of technology, more and more VLMs are emerging. Can VisRAG support more models as retrievers, such as Qwen2VL, internvl, etc.

**Comment by tcy6** [comment]
> With the development of technology, more and more VLMs are emerging. Can VisRAG support more models as retrievers, such as Qwen2VL, internvl, etc.

Absolutely! We are planning to integrate `Qwen2VL`-based retrievers in the near future, with support expected to roll out in about three weeks. Stay tuned!

**Comment by michaelbridge** [comment]
Hi @tcy6, was there ever any activity on this front? There are several interesting vision models now available including qwen3-vl, etc.
