### ISSUE TITLE
微调训练数据集格式问题

### ISSUE THREAD

**Issue by tuncha** [OpenBMB/VisRAG#32]
感谢您的开源代码，我想使用自定义数据集进行微调VisRAG-Ret，我注意到parquet文件内的image字段有点特殊非常长，请问它是直接将图像读取成字节再进行base64编码得到的吗？下面是我打印了其中一条的结果，我如果想微调，数据集是否要保持一致的格式？
{
    "query": "which are the countries with Chinese speaking population other than China according to this infographic?",
    "image": {
        "bytes": "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAvgAjQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDpvF9vtntrkDhkKMfccj+f6VzYHNdx4mg87RmfGTC6vn0GSD......."
        "path": "1.png"
    },
    "source": "InfoVQA"
}

**Comment by tcy6** [comment]
> 感谢您的开源代码，我想使用自定义数据集进行微调VisRAG-Ret，我注意到parquet文件内的image字段有点特殊非常长，请问它是直接将图像读取成字节再进行base64编码得到的吗？下面是我打印了其中一条的结果，我如果想微调，数据集是否要保持一致的格式？ { "query": "which are the countries with Chinese speaking population other than China according to this infographic?", "image": { "bytes": "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAvgAjQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDpvF9vtntrkDhkKMfccj+f6VzYHNdx4mg87RmfGTC6vn0GSD......." "path": "1.png" }, "source": "InfoVQA" }

感谢您的关注！parquet文件内的`image`字段下的`bytes`字段是图像的字节，并没有将其编码为base64。如果需要微调的话，您需要保持`query`字段和`image`字段的格式一致，`source`字段不是必需的～

**Comment by zhuyr97** [comment]
> > 感谢您的开源代码，我想使用自定义数据集进行微调VisRAG-Ret，我注意到parquet文件内的image字段有点特殊非常长，请问它是直接将图像读取成字节再进行base64编码得到的吗？下面是我打印了其中一条的结果，我如果想微调，数据集是否要保持一致的格式？ { "query": "which are the countries with Chinese speaking population other than China according to this infographic?", "image": { "bytes": "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAvgAjQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDpvF9vtntrkDhkKMfccj+f6VzYHNdx4mg87RmfGTC6vn0GSD......." "path": "1.png" }, "source": "InfoVQA" }
> 
> 感谢您的关注！parquet文件内的`image`字段下的`bytes`字段是图像的字节，并没有将其编码为base64。如果需要微调的话，您需要保持`query`字段和`image`字段的格式一致，`source`字段不是必需的～

为何感觉有点自相矛盾呢？
1. 在近期更新数据生成代码中，‘imagebyte_to_save = base64.b64decode(img_base64)’ 其实就是编码为base64，而这里说明的是`bytes`字段是图像的字节？ 这个是不是存在什么内容没有解释清楚？
2. ‘保持`query`字段和`image`字段的格式一致’ 这个怎么理解呢

**Comment by tcy6** [comment]
> > > 感谢您的开源代码，我想使用自定义数据集进行微调VisRAG-Ret，我注意到parquet文件内的image字段有点特殊非常长，请问它是直接将图像读取成字节再进行base64编码得到的吗？下面是我打印了其中一条的结果，我如果想微调，数据集是否要保持一致的格式？ { "query": "which are the countries with Chinese speaking population other than China according to this infographic?", "image": { "bytes": "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAvgAjQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDpvF9vtntrkDhkKMfccj+f6VzYHNdx4mg87RmfGTC6vn0GSD......." "path": "1.png" }, "source": "InfoVQA" }
> > 
> > 
> > 感谢您的关注！parquet文件内的`image`字段下的`bytes`字段是图像的字节，并没有将其编码为base64。如果需要微调的话，您需要保持`query`字段和`image`字段的格式一致，`source`字段不是必需的～
> 
> @tcy6 为何感觉有点自相矛盾呢？
> 
> 1. 在近期更新数据生成代码中，‘imagebyte_to_save = base64.b64decode(img_base64)’ 其实就是编码为base64，而这里说明的是`bytes`字段是图像的字节？ 这个是不是存在什么内容没有解释清楚？
> 2. ‘保持`query`字段和`image`字段的格式一致’ 这个怎么理解呢

不好意思，有些细节我确实忘了澄清。
1. 我们造数据时确实是将图片编码为base64，但是在将数据集上传至HF时，我们发现如果选择保持图片格式为base64的话，便无法使用HF上的Data Viewer可视化图片，因此为了方便大家观察数据，我们将其转换为了bytes。
2. ‘保持`query`字段和`image`字段的格式一致’指的是`query`字段为`str`类型，`image`字段为`bytes`类型。

**Comment by katie312** [comment]
> 感谢您的开源代码，我想使用自定义数据集进行微调VisRAG-Ret，我注意到parquet文件内的image字段有点特殊非常长，请问它是直接将图像读取成字节再进行base64编码得到的吗？下面是我打印了其中一条的结果，我如果想微调，数据集是否要保持一致的格式？ { "query": "which are the countries with Chinese speaking population other than China according to this infographic?", "image": { "bytes": "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAvgAjQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDpvF9vtntrkDhkKMfccj+f6VzYHNdx4mg87RmfGTC6vn0GSD......." "path": "1.png" }, "source": "InfoVQA" }

您好，我最近也在准备微调visrag的retriever，仓库里/面好像没有提供微调脚本，请问是直接在官方train好的模型上继续用train的脚本吗～？感谢！
