### ISSUE TITLE
关于训练数据集的问题请教

### ISSUE THREAD

**Issue by Aeryn666** [OpenBMB/VisRAG#34]
作者您好，我看论文里说，visrag用的训练和测试数据集是基本按照ChartQA、PlotQA、ArxivQA等几个数据集的训练和测试数据集划分的，然后我看原数据集是包含query、image、answer的，想请问一下作者，在将原数据集做成训练集的的时候有没有保留answer的版本呢，或者说您在处理数据的时候有保留原数据集中相应的query-id之类的信息吗？
我想要找visrag训练数据集中每个query-docunment对的对应的answer，但是发现并不是都能找到，所以想问一下作者您，麻烦了～

**Comment by tcy6** [comment]
@Aeryn666 非常抱歉我们在处理训练数据的时候并没有保留`answer`或是`query-id`之类的信息，因为当时并没有想过把训练数据用到其他地方(ToT)
