### ISSUE TITLE
训练retriever出的模型结构和提供的retriever模型不一样，大佬帮忙看看？

### ISSUE THREAD

**Issue by rxmao** [OpenBMB/VisRAG#35]
训练命令：
bash scripts/train_retriever/train.sh 2048 16 4 0.02 1 true false config/deepspeed.json 1e-5 false wmean causal 1 true 2 false openbmb/MiniCPM-V-2 openbmb/VisRAG-Ret-Train-In-domain-data

**Comment by tcy6** [comment]
@rxmao 你好，请问模型结构具体哪里不一样呢，能截图看一下嘛

**Comment by rxmao** [comment]
> @rxmao 你好，请问模型结构具体哪里不一样呢，能截图看一下嘛

训练出的模型resampler.py、modeling_minicpmv.py、modeling_minicpm.py这些文件都没有

**Comment by tcy6** [comment]
> > @rxmao 你好，请问模型结构具体哪里不一样呢，能截图看一下嘛
> 
> 训练出的模型resampler.py、modeling_minicpmv.py、modeling_minicpm.py这些文件都没有@tcy6

@rxmao 是的，我们并没有在保存权重的目录下保存这些文件。如果您想要使用自己训练得到的权重进行推理的话，您可以手动把`VisRAG-Ret`仓库中的权重替换为您训练得到的权重，然后参照我们在`Hugging Face`上写的`Usage`代码通过`AutoModel`加载模型即可。

**Comment by rxmao** [comment]
> > > @rxmao 你好，请问模型结构具体哪里不一样呢，能截图看一下嘛
> > 
> > 
> > 训练出的模型resampler.py、modeling_minicpmv.py、modeling_minicpm.py这些文件都没有@tcy6
> 
> @rxmao 是的，我们并没有在保存权重的目录下保存这些文件。如果您想要使用自己训练得到的权重进行推理的话，您可以手动把`VisRAG-Ret`仓库中的权重替换为您训练得到的权重，然后参照我们在`Hugging Face`上写的`Usage`代码通过`AutoModel`加载模型即可。

已经解决，多谢大佬！
