### ISSUE TITLE
The file format of the training data

### ISSUE THREAD

**Issue by lmmlzn** [OpenBMB/VisRAG#5]
Could you please provide a sample file format of the training data? Thanks.

**Comment by tcy6** [comment]
Of course! Our training data is located at https://huggingface.co/datasets/openbmb/VisRAG-Ret-Train-In-domain-data and https://huggingface.co/datasets/openbmb/VisRAG-Ret-Train-Synthetic-data, and their schema is as follows:{
"query": xxx,
"image": xxx,
"source": xxx
}
The data type of the query field is text, the data type of the image field is bytes, and the data type of the source field is text, indicating which dataset this sample comes from.
Thank you very much for your question! We will add a description of the sample format to the huggingface dataset page next.
