### ISSUE TITLE
GPU memory required

### ISSUE THREAD

**Issue by Cloudcatcher888** [OpenBMB/VisRAG#7]
Thank you for your work. I want to know how many GBs is required to run retriever/demo.py.

**Comment by tcy6** [comment]
Our model has 3.43 billion parameters and utilizes the bfloat16 data type. I estimate that the maximum memory required to run demo.py will not exceed 15GB.

**Comment by Cloudcatcher888** [comment]
Thank you for your immediate reply. I found GPU may not support bfloat16, will it causes any problem to modify it to float32

**Comment by tcy6** [comment]
You're welcome! From what I understand, there won't be any problem changing bfloat16 to float32, but since we haven't actually tested it, you may need to test it yourself.

**Comment by tcy6** [comment]
> Thank you for your immediate reply. I found GPU may not support bfloat16, will it causes any problem to modify it to float32

Hello, we just tested the memory usage of demo.py under `bfloat16` and `float32`, which are `8273MiB` and `15667MiB` respectively. I hope this can help you.
