### ISSUE TITLE
测试代码的相关问题

### ISSUE THREAD

**Issue by Aeryn666** [OpenBMB/VisRAG#8]
作者您好，这篇文章特别精彩，就是我在跑evaluation代码的时候遇到了一个问题想请教一下。
我按照readme.md运行指令：bash scripts/eval_retriever/eval.sh 512 2048 16 8 wmean causal ArxivQA,ChartQA,MP-DocVQA,InfoVQA,PlotQA,SlideVQA <ckpt_path>，此处我的ckpt_path设置为从hf上下载的VisRAG模型。然后会出现报错如下：
![image](https://github.com/user-attachments/assets/4d898dd5-cc77-4d5a-8a2e-9c2a1d52a899)
即在VisRAG/src/openmatch/driver/eval.py的第82行出现报错信息，说config_json["_name_or_path"]不存在，请问是因为我的ckpt_path设置错误吗，那么ckpt_path应该是哪个模型呢，谢谢作者🙏

**Comment by tcy6** [comment]
抱歉，这个bug确实是我们的疏忽，现在bug已经修复，您可以clone最新的代码下来，或者是将第82行的`if "MiniCPM-V-2" in config_json["_name_or_path"]:`更改为`if "MiniCPM-V-2" in config_json["_name_or_path"] or 'VisRAG' in config_json["_name_or_path"]:`。
感谢您的提问！
